--Indices

CREATE INDEX id_tipo_hab ON HTA_HABITACION(TIPOHABITACION);
CREATE INDEX mantenimiento_hab ON HTA_HABITACION(MANTENIMIENTO);

CREATE INDEX rol_usuario ON HTA_USUARIO_SISTEMA(ROL);

CREATE INDEX id_habitacion ON HTA_RESERVA_HABITACION(IDHABITACION);
CREATE INDEX reser_completada ON HTA_RESERVA_HABITACION(COMPLETADA);
CREATE INDEX tipo_doc ON HTA_RESERVA_HABITACION(TIPODOCCLIENTE);

CREATE INDEX tipo_serv ON HTA_SERVICIO(TIPOSERVICIO);

CREATE INDEX id_reserva_consumo ON HTA_CONSUMO_SERVICIO(IDRESERVA);
CREATE INDEX id_servicio ON HTA_CONSUMO_SERVICIO(IDSERVICIO);

CREATE INDEX id_reserva_reserva ON HTA_RESERVA_DE_SERVICIO(IDRESERVAHABITACION);
CREATE INDEX id_servicio ON HTA_RESERVA_DE_SERVICIO(IDSERVICIO);


